# English Translation
T_TITLE="YuraCloud - v1.0.0"
T_MENU="MAIN MENU"
T_OPT1="Web Installer"
T_OPT2="DB Config"
T_OPT3="System Info"
T_OPT4="Start Web"
T_OPT5="Stop Web"
T_OPT6="Restart Web"
T_OPT7="Kill Process"
T_OPT8="Manual CMD"
T_OPT9="Tutorial"
T_OPT10="Alat Lanjutan"
T_OPT11="Ganti Bahasa"
T_OPT0="Keluar"
T_SELECT="Select Option"
T_BACK="Back to Main Menu"
