# Japanese Translation
T_TITLE="YuraCloud - v1.0.0"
T_MENU="メインメニュー"
T_OPT1="インストーラー"
T_OPT2="DB設定"
T_OPT3="システム情報"
T_OPT4="起動"
T_OPT5="停止"
T_OPT6="再起動"
T_OPT7="強制終了"
T_OPT8="手動コマンド"
T_OPT9="ヘルプ/チュートリアル"
T_OPT10="高度なツール"
T_OPT11="言語切替"
T_OPT0="終了"
T_SELECT="オプションを選択"
T_BACK="メインメニューに戻る"
