# Korean Translation
T_TITLE="YuraCloud - v1.0.0"
T_MENU="메인 메뉴"
T_OPT1="웹 설치 관리자"
T_OPT2="DB 구성"
T_OPT3="시스템 정보"
T_OPT4="웹 시작"
T_OPT5="웹 중지"
T_OPT6="웹 재시작"
T_OPT7="강제 종료"
T_OPT8="수동 명령"
T_OPT9="도움말/튜토리얼"
T_OPT10="고급 도구"
T_OPT11="언어 변경"
T_OPT0="종료"
T_SELECT="옵션 선택"
T_BACK="메인 메뉴로 돌아가기"
